prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

grafana:
  adminPassword: "study-password"
  persistence:
    enabled: true
    type: pvc
    size: 2Gi
    storageClassName: "zfs-nfs"
    accessModes:
      - ReadWriteOnce
  initChownData:
    enabled: false
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    runAsNonRoot: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "zfs-nfs"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: 7GB
    walCompression: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
    containers:
      - name: prometheus
        securityContext:
          readOnlyRootFilesystem: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 400m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "zfs-nfs"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
