prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

grafana:
  adminPassword: "study-password"
  persistence:
    enabled: true
    type: pvc
    size: 2Gi
    storageClassName: "zfs-nfs"
    accessModes:
      - ReadWriteOnce
  initChownData:
    enabled: false
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    runAsNonRoot: true
  extraInitContainers:
    - name: fix-permissions
      image: busybox:latest
      command: ['sh', '-c', 'chmod -R 775 /var/lib/grafana && chown -R 472:472 /var/lib/grafana']
      volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
      securityContext:
        runAsUser: 0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  alertmanagerSpec:
    replicas: 1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000
    initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ['sh', '-c', 'chmod -R 775 /alertmanager && chown -R 1000:2000 /alertmanager']
        volumeMounts:
          - name: alertmanager-kube-prometheus-stack-alertmanager-db
            mountPath: /alertmanager
        securityContext:
          runAsUser: 0
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "zfs-nfs"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    retentionSize: 7GB
    walCompression: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 2000
    initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ['sh', '-c', 'chmod -R 775 /prometheus && chown -R 1000:2000 /prometheus']
        volumeMounts:
          - name: prometheus-kube-prometheus-stack-prometheus-db
            mountPath: /prometheus
        securityContext:
          runAsUser: 0
    containers:
      - name: prometheus
        securityContext:
          readOnlyRootFilesystem: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 400m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "zfs-nfs"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
