apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: 78.3.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/helm-values/kube-prometheus-stack/values.yml
    - repoURL: https://github.com/frederycksales/sre-homelab-apps
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind
        - '.spec.template.metadata.annotations."checksum/config"'
