# sre-homelab-apps/apps/nfs-provisioner.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  labels:
    app.kubernetes.io/name: nfs-provisioner
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.18
      helm:
        releaseName: nfs-provisioner
        valueFiles:
          - $values/helm-values/nfs-provisioner/values.yml
    - repoURL: https://github.com/frederycksales/sre-homelab-apps
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
