# sre-homelab-apps/apps/podinfo.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: "6.9.2"
      helm:
        valueFiles:
          - $values/helm-values/podinfo/values.yml
    - repoURL: https://github.com/frederycksales/sre-homelab-apps
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
