loki:
  persistence:
    enabled: true
    storageClassName: "zfs-nfs"
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

promtail:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

grafana:
  enabled: false
  
prometheus:
  enabled: false
