name: Validate Kubernetes Manifests

# Run on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-manifests:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Lint YAML files under apps/
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./apps

      # Validate Kubernetes schemas with Kubeconform
      - name: Validate Kubernetes schemas with Kubeconform
        uses: yannh/kubeconform-action@v0.4.14
        with:
          kubernetes-version: "1.28.0"
          skip-crd: true
          files: ./apps