# .github/workflows/validate.yml
name: Validate Kubernetes Manifests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-manifests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Lint YAML files for basic syntax errors
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./apps

      # Step 3: Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      # Step 4: Run Kubeconform using the official Docker image
      - name: Run Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -kubernetes-version 1.28.0 -ignore-missing-schemas ./apps"